[options]
addons_path = /home/odoo/workspace/Odoo_17/odoo/addons,/home/odoo/workspace/Odoo_17/my_adds/real_estate_project

admin_passwd = a
xmlrpc_port = 8017
longpolling_port = 7017
limit_time_cpu = 180000
limit_time_real = 360000
log_db_level = debug
log_db = True
# log_db_level = error
# log_handler = :DEBUG
# log_handler = :INFO
# log_handler = :ERROR
# log_level = info
log_level = info
log_handler = odoo.addons.license_verifier:DEBUG
# log_level = warn
# log_level = error
logfile = /home/odoo/workspace/Odoo_17/Odoo_17.log
csv_internal_sep = ,
data_dir = /home/odoo/.local/share/Odoo
db_host = False
db_maxconn = 64
db_name =
db_password = False
db_port = False
db_sslmode = prefer
db_template = template0
db_user = False
dbfilter =
# demo = {}
dev = all
http_interface =
http_port = 8017
import_partial =
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_real_cron = -1
list_db = True
max_cron_threads = 2
proxy_mode = False
server_wide_modules = base,web
test_enable = False
test_file =
test_tags = None
transient_age_limit = 1.0
translate_modules = ['all']
without_demo = True
workers = 0
